# Author: Michael Bopp
# Filename: Docker-compose.yml
# Description: Docker-compose for CS330 Presentation.
# Date Created: 8/25/23
# Last Edited: 8/27/23

# Commands to run:
# docker-compose run cs330_service

# Way to offer more docker-compose granularity.
# Start building an image and launch a container.
# docker-compose up --build
# Stop container and remove it (image persists).
# docker-compose down

version: '3'
services:
  cs330_service:
    build:     # Make sure to name your environmental variable to the CS330_Presentation path.
      context: ${BUILD_CONTEXT:-default_path}
      dockerfile: Dockerfile  # Assuming your Dockerfile is in the above directory
    image: alpine:CS330  # image:tag
    volumes: # This is passing a slice of your OS filesystem into the container.
      - ${BUILD_CONTEXT:-default_path}:/workspace
    stdin_open: true  # -i flag in `docker run`
    tty: true         # -t flag in `docker run`
    command: sh       # Start an Alpine Linux shell.
    ports:
      - "8080:80/tcp"