# Author: Michael Bopp
# Filename: Taskfile.yml
# Description: Similar to a Makefile w/o GNU dependency & utilizing YAML.
# Date Created: 8/22/23
# Last Edited: 8/28/23
# Dependency: https://taskfile.dev/installation/

# Useful Commands:
# task --list-all
# task --list-all --json
# task --list --json

version: '3'

vars:
  CURRENT_DIR:
    sh: pwd

tasks:
  print-dir:
    cmds:
      - echo '{{.CURRENT_DIR}}'
    aliases: ['p']
  build:
    cmds:
      - GOOS=js GOARCH=wasm go build -o ./wasm/main.wasm ./wasm/main.go
    aliases: ['b']
  server:
    cmds:
      - |
        if [ "{{OS}}" = "windows" ]; then
          python ./wasm/server.py
        else
          python3 ./wasm/server.py
        fi
    aliases: ['s']
  clean:
    cmds:
      - |
        if [ "{{OS}}" = "windows" ]; then
          cmd /c del *.out *.exe *.wasm
        else
          rm -f *.out *.exe *.wasm
        fi
    aliases: ['c']
  hello:
    cmds:
      - go run hello.go
    aliases: ['h']
  tree:
    cmds:
      - go run btree.go 10
    aliases: ['t']
  go:
    cmds:
      - go run goroutine.go
    aliases: ['g']